/obj/machinery/atmospherics/relaymove(mob/living/user, direction)
	if(direction in GLOB.cardinal)
		return ..(user, direction)
	var/new_direction = turn(direction, 45)
	return ..(user, new_direction)
